name: agendamento_pet
description: AgendamentoPet.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
cached_network_image: ^3.2.3
flutter_svg: ^2.0.7
flutter_bloc: ^8.1.3
equatable: ^2.0.5
shared_preferences: ^2.2.0
connectivity_plus: ^5.0.2
dotted_border: ^2.0.0+3
flutter_svg_provider: ^1.0.7

cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/MulishRomanBlack.ttf
          weight: 900
        - asset: assets/fonts/MulishRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/MulishRomanBold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/MulishRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/MulishRomanRegular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400

